@startuml diagram

object Persona {

 rut
 nombre
 genero
 email
 fono
 movil
 unidad academica
 rol
}

object Vehiculo {

 patente
 marca
 modelo
 año
 color
 observacion

}

object Acceso {
 uid
 hora entrada
 patente
 porteria
}

Acceso "0..*" --> "1" Vehiculo: Registra
Vehiculo "1" --> "1" Persona: Asocia
@enduml
