@startuml diagram

object Persona {
 uid
 nombre
 rut
 genero
 fono
 email
}

object Vehiculo {
 patente
 marca
 modelo
 año
 observacion
 logo
}

object Acceso {
 timestamp
 patente
 porteria
}

Acceso "1" --> "1" Vehiculo: Registra
Vehiculo "1" --> "1" Persona: Asocia
@enduml
