@startuml diagram

object Persona {
 uid
 nombre
 rut
 genero
 email
 fono
}

object Vehiculo {
 uid
 patente
 marca
 modelo
 año
 observacion
 logo
}

object Acceso {
 uid
 hora
 patente
 porteria
}

Acceso "0..*" --> "1" Vehiculo: Registra
Vehiculo "1" --> "1" Persona: Asocia
@enduml
