@startuml diagram

object Persona {
 nombre
 rut
}

object Vehiculo {
 patente
}

object Acceso {
 timestamp
 patente
 porteria
}

Acceso "1" --> "1" Vehiculo: Registra
Vehiculo "1" --> "1" Persona: Asocia
@enduml